<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="213511" started-at="2017-08-04T09:06:46Z" finished-at="2017-08-04T09:10:20Z">
    <groups>
      <group name="add">
        <method signature="WhayerMetaDataManagerImplTest.savleAlarmMessageLevelMetaListTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@61167c80]" name="savleAlarmMessageLevelMetaListTest" class="com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest"/>
        <method signature="WhayerMetaDataManagerImplTest.savleAlarmMessageLevelMetaTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@61167c80]" name="savleAlarmMessageLevelMetaTest" class="com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest"/>
      </group> <!-- add -->
    </groups>
    <test name="Default test" duration-ms="213511" started-at="2017-08-04T09:06:46Z" finished-at="2017-08-04T09:10:20Z">
      <class name="com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@61167c80]" name="beforeTest" is-config="true" duration-ms="2088" started-at="2017-08-04T17:06:46Z" finished-at="2017-08-04T17:06:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="deleteAll()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@61167c80]" name="deleteAll" duration-ms="211077" started-at="2017-08-04T17:06:48Z" finished-at="2017-08-04T17:10:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[按照MessageSourceTypeMeta类型删除失败! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 按照MessageSourceTypeMeta类型删除失败! expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest.deleteAll(WhayerMetaDataManagerImplTest.java:258)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteAll -->
        <test-method status="PASS" signature="savleAlarmMessageLevelMetaListTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@61167c80]" name="savleAlarmMessageLevelMetaListTest" duration-ms="155" started-at="2017-08-04T17:10:20Z" finished-at="2017-08-04T17:10:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- savleAlarmMessageLevelMetaListTest -->
        <test-method status="PASS" signature="savleAlarmMessageLevelMetaTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@61167c80]" name="savleAlarmMessageLevelMetaTest" duration-ms="142" started-at="2017-08-04T17:10:20Z" finished-at="2017-08-04T17:10:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- savleAlarmMessageLevelMetaTest -->
        <test-method status="PASS" signature="updateTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@61167c80]" name="updateTest" duration-ms="14" started-at="2017-08-04T17:10:20Z" finished-at="2017-08-04T17:10:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateTest -->
      </class> <!-- com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
