<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WY-20170801CARC" name="com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest" tests="4" failures="1" timestamp="4 Aug 2017 09:10:20 GMT" time="211.388" errors="0">
  <testcase name="deleteAll" time="211.077" classname="com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest">
    <failure type="java.lang.AssertionError" message="按照MessageSourceTypeMeta类型删除失败! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: 按照MessageSourceTypeMeta类型删除失败! expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest.deleteAll(WhayerMetaDataManagerImplTest.java:258)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- deleteAll -->
  <testcase name="updateTest" time="0.014" classname="com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest"/>
  <testcase name="savleAlarmMessageLevelMetaListTest" time="0.155" classname="com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest"/>
  <testcase name="savleAlarmMessageLevelMetaTest" time="0.142" classname="com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest"/>
</testsuite> <!-- com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest -->
